# Create a new record with an initial meta data

# Checkpoint timestamp, denoting the time of creation for record
builtin_interfaces/Time stamp

# Checkpoint nonce, denoting the ransom seed of hash chain for record
std_msgs/ByteMultiArray nonce

# Checkpoint name, denoting the respective name for record
string name

# Checkpoint type, denoting the respective type for record
string type

# Checkpoint format, denoting the respective serialization for record
string serialization_format

---
bool success
